#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clone source code
      run: |
        wget --no-check-certificate https://archive.openwrt.org/releases/21.02.0/targets/x86/64/openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xvJf openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        #cd openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64 && svn co https://github.com/coolsnowwolf/lede/trunk/package
        git clone https://github.com/coolsnowwolf/lede && cp lede/package/lean/ openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64/package/ -R
        echo "src-git helloworld https://github.com/fw876/helloworld.git" >> openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64/feeds.conf.default
    - name: Update feeds
      run: cd openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64 && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64 && ./scripts/feeds install -a
     
    - name: Setup Debug Session
      uses: fyfh/debugger-action@master

    - name: Download package
      run: |
        cd openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64 && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64
        echo -e "$(nproc) thread build."
        make package/feeds/luci/luci-base/compile V=s
        make -j$(nproc) V=s
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64
        path: openwrt-sdk-21.02.0-x86-64_gcc-8.4.0_musl.Linux-x86_64/bin
